INSERT INTO ROOM(NAME, ROOM_NUMBER, BED_INFO) VALUES ('Piccadilly', 'P1', '1Q');
INSERT INTO ROOM(NAME, ROOM_NUMBER, BED_INFO) VALUES ('Piccadilly', 'P2', '1Q');
INSERT INTO ROOM(NAME, ROOM_NUMBER, BED_INFO) VALUES ('Piccadilly', 'P3', '1Q');
INSERT INTO ROOM(NAME, ROOM_NUMBER, BED_INFO) VALUES ('Piccadilly', 'P4', '2D');
INSERT INTO ROOM(NAME, ROOM_NUMBER, BED_INFO) VALUES ('Piccadilly', 'P5', '2D');
INSERT INTO ROOM(NAME, ROOM_NUMBER, BED_INFO) VALUES ('Piccadilly', 'P6', '2D');
INSERT INTO ROOM(NAME, ROOM_NUMBER, BED_INFO) VALUES ('Cambridge', 'C1', '1K');
INSERT INTO ROOM(NAME, ROOM_NUMBER, BED_INFO) VALUES ('Cambridge', 'C2', '1K');
INSERT INTO ROOM(NAME, ROOM_NUMBER, BED_INFO) VALUES ('Cambridge', 'C3', '1K');


INSERT INTO EMPLOYEE(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, POSITION) VALUES ('0eabf2d2-7975-4757-9434-19bd3cf7c03c', 'John', 'Doe','HOUSEKEEPING');
INSERT INTO EMPLOYEE(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, POSITION) VALUES ('8c70afca-7306-41e3-beed-7044bb765aed', 'Mark', 'Dean','SECURITY');
INSERT INTO EMPLOYEE(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, POSITION) VALUES ('853ed27b-39f3-404e-a203-533b6d68eb47', 'Mona', 'Lisa','FRONT_DESK');
INSERT INTO EMPLOYEE(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, POSITION) VALUES ('2ebbc074-af90-440f-a2e1-9a01a9b9929e', 'Tom', 'Cat','CONCIERGE');